#pragma once
#include "Actions\Action.h"
#include "AddFigureAction\AddCircleAction.h"
#include "AddFigureAction\AddLineAction.h"
#include "AddFigureAction\AddRectAction.h"
#include "AddFigureAction\AddTriAction.h"
#include "SendBack BringFront Action\BringFrontAction.h"
#include "SendBack BringFront Action\SendBackAction.h"
#include "Move Resize Rotate Zoom Action\MoveAction.h"
#include "Move Resize Rotate Zoom Action\ResizeAction.h"
#include "Save Load Action\SaveAction.h" 
#include "Save Load Action\LoadAction.h"
#include "Move Resize Rotate Zoom Action\RotateAction.h"
#include "Copy Cut Delete Action\CopyAction.h"
#include "Copy Cut Delete Action\\PasteAction.h"
#include "Copy Cut Delete Action\\CutAction.h"
#include "Copy Cut Delete Action\\DeleteAction.h"
#include "SelectAction\SelectAction.h"
#include "Color Border ChangeAction\ChangeColorAction.h"
#include "Color Border ChangeAction\ChangeBackgroundColor.h"
#include "Color Border ChangeAction\ChangeFillColor.h"
#include "Color Border ChangeAction\ChangeBorderColor.h"
#include "Color Border ChangeAction\ChangeBorderWidth.h"
#include "Move Resize Rotate Zoom Action\ZoomAction.h"
#include "Undo Redo Action\UndoAction.h"
#include "Undo Redo Action\RedoAction.h"
#include "Games\Pick and Hide\PickAndHide.h"
#include "Games\ScrambleAndFind.h"
#include "ExitAction.h"